version: "3.9"
services:
  db:
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"']
      interval: 60s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  database:
