version: "3.9"
services:
  web:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.web
    container_name: waze_web
    ports:
      - "9997:3000"
    networks:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: waze_db
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"']
      interval: 60s
      timeout: 5s
      retries: 5
    restart: always

  scrapper:
    build:
      context: .
      dockerfile: Dockerfile.scrapper
      network: host
    container_name: waze_scrapper
    env_file:
      - .env
    networks:
      - db
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  db:
