# Install dependencies only when needed
FROM node:18 AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
WORKDIR /app
COPY package.json ./
RUN npm install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:18 AS builder
WORKDIR /app
COPY . .
COPY .env* ./
COPY --from=deps /app/node_modules ./node_modules

ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}

RUN npx prisma generate
RUN npm run build && npm install --omit=dev --ignore-scripts --prefer-offline

# Production image, copy all the files and run next
FROM node:18 AS runner
WORKDIR /app

ENV NODE_ENV production

# You only need to copy next.config.mjs if you are NOT using the default configuration
COPY .env* ./
COPY --from=builder /app/next.config.mjs ./
# COPY --from=builder /app/public ./public
COPY --from=builder --chown=root:root /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

RUN chown -R root:root node_modules/@prisma

COPY prisma ./prisma

EXPOSE 3000
ENV PORT 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

CMD npx prisma migrate deploy && node_modules/.bin/next start -p 3000
