import type { WazeCategory } from "@/app/wazeCategories";
import { z } from "zod";

export const heatmapResponseSchema = z.union([
  z.object({ count: z.number(), lat: z.number(), lon: z.number() }).array(),
  z.literal(null),
]);

export const typeSchema = z.union([
  z.literal("ACCIDENT"),
  z.literal("HAZARD"),
  z.literal("ROAD_CLOSED"),
  z.literal("JAM"),
  z.literal("POLICE"),
  z.literal("CHITCHAT"),
]);

export type WazeType = z.output<typeof typeSchema>;

export const subtypeSchema = z.union([
  // Accident
  z.literal("ACCIDENT_MINOR"),
  z.literal("ACCIDENT_MAJOR"),

  // Hazard
  // Hazard on road
  z.literal("HAZARD_ON_ROAD"),
  z.literal("HAZARD_ON_ROAD_CAR_STOPPED"),
  z.literal("HAZARD_ON_ROAD_CONSTRUCTION"),
  z.literal("HAZARD_ON_ROAD_EMERGENCY_VEHICLE"),
  z.literal("HAZARD_ON_ROAD_ICE"),
  z.literal("HAZARD_ON_ROAD_LANE_CLOSED"),
  z.literal("HAZARD_ON_ROAD_OBJECT"),
  z.literal("HAZARD_ON_ROAD_OIL"),
  z.literal("HAZARD_ON_ROAD_POT_HOLE"),
  z.literal("HAZARD_ON_ROAD_ROAD_KILL"),
  z.literal("HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT"),
  // Hazard on shoulder
  z.literal("HAZARD_ON_SHOULDER"),
  z.literal("HAZARD_ON_SHOULDER_ANIMALS"),
  z.literal("HAZARD_ON_SHOULDER_CAR_STOPPED"),
  z.literal("HAZARD_ON_SHOULDER_MISSING_SIGN"),
  // Hazard weather
  z.literal("HAZARD_WEATHER"),
  z.literal("HAZARD_WEATHER_FLOOD"),
  z.literal("HAZARD_WEATHER_FOG"),
  z.literal("HAZARD_WEATHER_FREEZING_RAIN"),
  z.literal("HAZARD_WEATHER_HAIL"),
  z.literal("HAZARD_WEATHER_HEAT_WAVE"),
  z.literal("HAZARD_WEATHER_HEAVY_RAIN"),
  z.literal("HAZARD_WEATHER_HEAVY_SNOW"),
  z.literal("HAZARD_WEATHER_HURRICANE"),
  z.literal("HAZARD_WEATHER_MONSOON"),
  z.literal("HAZARD_WEATHER_TORNADO"),

  // Road closed
  z.literal("ROAD_CLOSED"),
  z.literal("ROAD_CLOSED_HAZARD"),
  z.literal("ROAD_CLOSED_CONSTRUCTION"),
  z.literal("ROAD_CLOSED_EVENT"),

  // Jam
  z.literal("JAM_LIGHT_TRAFFIC"),
  z.literal("JAM_MODERATE_TRAFFIC"),
  z.literal("JAM_HEAVY_TRAFFIC"),
  z.literal("JAM_STAND_STILL_TRAFFIC"),

  // Police
  z.literal("POLICE_VISIBLE"),
  z.literal("POLICE_HIDDEN"),
]);

export type WazeSubtype = z.output<typeof subtypeSchema>;

export const toDatabase: Record<WazeCategory, WazeCategory[]> = {
  ACCIDENT: ["ACCIDENT", "ACCIDENT_MINOR", "ACCIDENT_MAJOR"],
  ACCIDENT_MINOR: ["ACCIDENT_MINOR"],
  ACCIDENT_MAJOR: ["ACCIDENT_MAJOR"],

  HAZARD: [
    "HAZARD",

    "HAZARD_ON_ROAD",
    "HAZARD_ON_ROAD_CAR_STOPPED",
    "HAZARD_ON_ROAD_CONSTRUCTION",
    "HAZARD_ON_ROAD_EMERGENCY_VEHICLE",
    "HAZARD_ON_ROAD_ICE",
    "HAZARD_ON_ROAD_LANE_CLOSED",
    "HAZARD_ON_ROAD_OBJECT",
    "HAZARD_ON_ROAD_OIL",
    "HAZARD_ON_ROAD_POT_HOLE",
    "HAZARD_ON_ROAD_ROAD_KILL",
    "HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT",

    "HAZARD_ON_SHOULDER",
    "HAZARD_ON_SHOULDER_ANIMALS",
    "HAZARD_ON_SHOULDER_CAR_STOPPED",
    "HAZARD_ON_SHOULDER_MISSING_SIGN",

    "HAZARD_WEATHER",
    "HAZARD_WEATHER_FLOOD",
    "HAZARD_WEATHER_FOG",
    "HAZARD_WEATHER_FREEZING_RAIN",
    "HAZARD_WEATHER_HAIL",
    "HAZARD_WEATHER_HEAT_WAVE",
    "HAZARD_WEATHER_HEAVY_RAIN",
    "HAZARD_WEATHER_HEAVY_SNOW",
    "HAZARD_WEATHER_HURRICANE",
    "HAZARD_WEATHER_MONSOON",
    "HAZARD_WEATHER_TORNADO",
  ],
  HAZARD_ON_ROAD: [
    "HAZARD_ON_ROAD",
    "HAZARD_ON_ROAD_CAR_STOPPED",
    "HAZARD_ON_ROAD_CONSTRUCTION",
    "HAZARD_ON_ROAD_EMERGENCY_VEHICLE",
    "HAZARD_ON_ROAD_ICE",
    "HAZARD_ON_ROAD_LANE_CLOSED",
    "HAZARD_ON_ROAD_OBJECT",
    "HAZARD_ON_ROAD_OIL",
    "HAZARD_ON_ROAD_POT_HOLE",
    "HAZARD_ON_ROAD_ROAD_KILL",
    "HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT",
  ],
  HAZARD_ON_ROAD_CAR_STOPPED: ["HAZARD_ON_ROAD_CAR_STOPPED"],
  HAZARD_ON_ROAD_CONSTRUCTION: ["HAZARD_ON_ROAD_CONSTRUCTION"],
  HAZARD_ON_ROAD_EMERGENCY_VEHICLE: ["HAZARD_ON_ROAD_EMERGENCY_VEHICLE"],
  HAZARD_ON_ROAD_ICE: ["HAZARD_ON_ROAD_ICE"],
  HAZARD_ON_ROAD_LANE_CLOSED: ["HAZARD_ON_ROAD_LANE_CLOSED"],
  HAZARD_ON_ROAD_OBJECT: ["HAZARD_ON_ROAD_OBJECT"],
  HAZARD_ON_ROAD_OIL: ["HAZARD_ON_ROAD_OIL"],
  HAZARD_ON_ROAD_POT_HOLE: ["HAZARD_ON_ROAD_POT_HOLE"],
  HAZARD_ON_ROAD_ROAD_KILL: ["HAZARD_ON_ROAD_ROAD_KILL"],
  HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT: ["HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT"],

  HAZARD_ON_SHOULDER: [
    "HAZARD_ON_SHOULDER",
    "HAZARD_ON_SHOULDER_ANIMALS",
    "HAZARD_ON_SHOULDER_CAR_STOPPED",
    "HAZARD_ON_SHOULDER_MISSING_SIGN",
  ],
  HAZARD_ON_SHOULDER_ANIMALS: ["HAZARD_ON_SHOULDER_ANIMALS"],
  HAZARD_ON_SHOULDER_CAR_STOPPED: ["HAZARD_ON_SHOULDER_CAR_STOPPED"],
  HAZARD_ON_SHOULDER_MISSING_SIGN: ["HAZARD_ON_SHOULDER_MISSING_SIGN"],

  HAZARD_WEATHER: [
    "HAZARD_WEATHER",
    "HAZARD_WEATHER_FLOOD",
    "HAZARD_WEATHER_FOG",
    "HAZARD_WEATHER_FREEZING_RAIN",
    "HAZARD_WEATHER_HAIL",
    "HAZARD_WEATHER_HEAT_WAVE",
    "HAZARD_WEATHER_HEAVY_RAIN",
    "HAZARD_WEATHER_HEAVY_SNOW",
    "HAZARD_WEATHER_HURRICANE",
    "HAZARD_WEATHER_MONSOON",
    "HAZARD_WEATHER_TORNADO",
  ],
  HAZARD_WEATHER_FLOOD: ["HAZARD_WEATHER_FLOOD"],
  HAZARD_WEATHER_FOG: ["HAZARD_WEATHER_FOG"],
  HAZARD_WEATHER_FREEZING_RAIN: ["HAZARD_WEATHER_FREEZING_RAIN"],
  HAZARD_WEATHER_HAIL: ["HAZARD_WEATHER_HAIL"],
  HAZARD_WEATHER_HEAT_WAVE: ["HAZARD_WEATHER_HEAT_WAVE"],
  HAZARD_WEATHER_HEAVY_RAIN: ["HAZARD_WEATHER_HEAVY_RAIN"],
  HAZARD_WEATHER_HEAVY_SNOW: ["HAZARD_WEATHER_HEAVY_SNOW"],
  HAZARD_WEATHER_HURRICANE: ["HAZARD_WEATHER_HURRICANE"],
  HAZARD_WEATHER_MONSOON: ["HAZARD_WEATHER_MONSOON"],
  HAZARD_WEATHER_TORNADO: ["HAZARD_WEATHER_TORNADO"],

  ROAD_CLOSED: [
    "ROAD_CLOSED",
    "ROAD_CLOSED_HAZARD",
    "ROAD_CLOSED_CONSTRUCTION",
    "ROAD_CLOSED_EVENT",
  ],
  ROAD_CLOSED_HAZARD: ["ROAD_CLOSED_HAZARD"],
  ROAD_CLOSED_CONSTRUCTION: ["ROAD_CLOSED_CONSTRUCTION"],
  ROAD_CLOSED_EVENT: ["ROAD_CLOSED_EVENT"],

  JAM: [
    "JAM",
    "JAM_LIGHT_TRAFFIC",
    "JAM_MODERATE_TRAFFIC",
    "JAM_HEAVY_TRAFFIC",
    "JAM_STAND_STILL_TRAFFIC",
  ],
  JAM_LIGHT_TRAFFIC: ["JAM_LIGHT_TRAFFIC"],
  JAM_MODERATE_TRAFFIC: ["JAM_MODERATE_TRAFFIC"],
  JAM_HEAVY_TRAFFIC: ["JAM_HEAVY_TRAFFIC"],
  JAM_STAND_STILL_TRAFFIC: ["JAM_STAND_STILL_TRAFFIC"],

  POLICE: ["POLICE", "POLICE_VISIBLE", "POLICE_HIDDEN"],
  POLICE_VISIBLE: ["POLICE_VISIBLE"],
  POLICE_HIDDEN: ["POLICE_HIDDEN"],

  CHITCHAT: ["CHITCHAT"],
};
