import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import { GoogleBoundary } from "./googleBoundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const { NEXT_PUBLIC_GOOGLE_MAPS_API_KEY } = process.env;

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => (
  <html lang="en">
    <head>
      <script
        async={true}
        src={`https://maps.googleapis.com/maps/api/js?key=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&loading=async&libraries=visualization`}
      />
    </head>
    <body className={inter.className}>
      <GoogleBoundary>{children}</GoogleBoundary>
    </body>
  </html>
);

export default RootLayout;
